config/routes.rb
Rails.application.routes.draw do
  resources :prefectures
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/prefecture.rb
# frozen_string_literal: true

class Prefecture < ActiveYaml::Base
  set_root_path 'master'
  set_filename 'prefectures'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/prefectures_controller.rb
class PrefecturesController < ApplicationController
  before_action :set_prefecture, only: [:show, :edit, :update, :destroy]

  # GET /prefectures
  # GET /prefectures.json
  def index
    @prefectures = Prefecture.all
  end

  # GET /prefectures/1
  # GET /prefectures/1.json
  def show
  end

  # GET /prefectures/new
  def new
    @prefecture = Prefecture.new
  end

  # GET /prefectures/1/edit
  def edit
  end

  # POST /prefectures
  # POST /prefectures.json
  def create
    @prefecture = Prefecture.new(prefecture_params)

    respond_to do |format|
      if @prefecture.save
        format.html { redirect_to @prefecture, notice: 'Prefecture was successfully created.' }
        format.json { render :show, status: :created, location: @prefecture }
      else
        format.html { render :new }
        format.json { render json: @prefecture.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /prefectures/1
  # PATCH/PUT /prefectures/1.json
  def update
    respond_to do |format|
      if @prefecture.update(prefecture_params)
        format.html { redirect_to @prefecture, notice: 'Prefecture was successfully updated.' }
        format.json { render :show, status: :ok, location: @prefecture }
      else
        format.html { render :edit }
        format.json { render json: @prefecture.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /prefectures/1
  # DELETE /prefectures/1.json
  def destroy
    @prefecture.destroy
    respond_to do |format|
      format.html { redirect_to prefectures_url, notice: 'Prefecture was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_prefecture
      @prefecture = Prefecture.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def prefecture_params
      params.require(:prefecture).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/prefectures_helper.rb
module PrefecturesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PlayWithActiveHash</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/prefectures/_form.html.erb
<%= form_with(model: prefecture, local: true) do |form| %>
  <% if prefecture.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(prefecture.errors.count, "error") %> prohibited this prefecture from being saved:</h2>

      <ul>
      <% prefecture.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/prefectures/edit.html.erb
<h1>Editing Prefecture</h1>

<%= render 'form', prefecture: @prefecture %>

<%= link_to 'Show', @prefecture %> |
<%= link_to 'Back', prefectures_path %>

app/views/prefectures/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Prefectures</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @prefectures.each do |prefecture| %>
      <tr>
        <td><%= prefecture.name %></td>
        <td><%= link_to 'Show', prefecture %></td>
        <td><%= link_to 'Edit', edit_prefecture_path(prefecture) %></td>
        <td><%= link_to 'Destroy', prefecture, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Prefecture', new_prefecture_path %>

app/views/prefectures/new.html.erb
<h1>New Prefecture</h1>

<%= render 'form', prefecture: @prefecture %>

<%= link_to 'Back', prefectures_path %>

app/views/prefectures/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @prefecture.name %>
</p>

<%= link_to 'Edit', edit_prefecture_path(@prefecture) %> |
<%= link_to 'Back', prefectures_path %>